# This is a basic workflow that is manually triggered

name: Reset Database

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  clear-database:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        
    - name: clear database
      run: echo "{}" > db.json
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "clear database"
